// examen-Angular/src/app/component/carrito-compra/carrito-compra.component.ts
import { Component, OnInit } from '@angular/core';
import { ConexionService } from '../../services/conexion.service';
@Component({
  selector: 'app-carrito-compra',
  templateUrl: './carrito-compra.component.html',
  styleUrls: ['./carrito-compra.component.css']
})
export class CarritoCompraComponent implements OnInit {

  constructor(public servicio: ConexionService) { }

  ngOnInit() {
    this.addCompras();
  }
  carrito = [];
  total :any;
  addCompras(){
    this.carrito = this.servicio.carrito
    this.total = this.servicio.totales;
  }

  pagar(){
    this.carrito.forEach(element => {
      console.log(element.id)
      this.servicio.updateItem(element.uniDispo,element.nomProducto,element.imagen,element.id);
    });
    this.servicio.carrito = [];
  }
}

<barra-menu></barra-menu>
<div class="container">
  <div class="row" >
        <div class="col-8 mt-5 ">
          <div class="col-12 mt-3" *ngFor="let item of carrito">
              <div class="row">
                  <div class="col-5">
                      <img class="card-img-top" [src]="'../assets/img/' + item.imagen">
                    </div>
                    <div class="col-7">
                      <h5><span> {{item.nomProducto}}</span></h5>
                      <h6><span>Unidades: {{item.cantidadProducto}}</span></h6>
                      <h6><span>Subtotal: ${{item.subTotal}}</span></h6>
                    </div>
              </div>
          </div>
        </div>
        
        <div class="col-4 mt-5">
            <div class="card">
                <div class="card-header">
                 Factura de pago
                </div>
                <div class="card-body">
                  <h5 class="card-title">Total a pagar</h5>
                  <p class="card-text">Pago:{{total}} </p>
                  <a (click)="pagar()" class="btn btn-primary">Pagar!!</a>
                </div>
              </div>
        </div>
    </div>   
  </div>

// examen-react/src/componentes/carrito-compra/index.js
import React, {Component} from 'react';
import Compra from '../carrito-compra/compra.jsx'
import Header2 from '../header/navbar.js'

class Carrito extends Component {
    constructor(){
        super()
       this.state = {
           compras:[],
           totalCompra:0
       }
        
    }

    componentDidMount(){
        let carrito = JSON.parse(localStorage.getItem('compra'))
        let total = localStorage.getItem('pago')
        this.setState({compras: carrito, totalCompra: total})
        console.log(total)
    }


    pago(){
        localStorage.setItem('pago',0)
        localStorage.setItem('aviso',0)
    }

    render(){
        return(
           <div className="container">
           <Header2/>
            <div className="row">
            <div className="col-8 mt-5 ">
                {this.state.compras.map(compra => {
                    return(
                      <Compra
                      precio = {compra.precio}
                      cantidad = {compra.cantidad}
                      imagen = {compra.imagen}
                      nombre = {compra.nombre}
                      />
                    )
                })}              
            </div>
            <div className="col-4 mt-5">
                <div className="card">
                    <div className="card-header">
                     Factura de pago
                    </div>
                    <div className="card-body">
                      <h5 className="card-title">Total a pagar</h5>
                      <p className="card-text">Pago: {this.state.totalCompra}</p>
                      <a onClick={()=>this.pago()} className="btn btn-primary">Pagar</a>
                    </div>
                  </div>
            </div>
        </div>   </div>
        );
    }
}

export default Carrito;
