// examen-react/src/componentes/Login/index.js
import React, {Component} from 'react';
import firebase from 'firebase'
import {db_config} from '../configuracion.js'
import 'firebase/database'


class Login extends Component {

    constructor(){  
      
        super();
        this.state = {
            usuario:[]
        }
        this.app = firebase.initializeApp(db_config);
        this.db = this.app.database().ref().child('usuarios')
    }
    
    componentDidMount(){
        const {usuario}=this.state;
        this.db.on('child_added', snap=>{
            usuario.push({
                user: snap.val().correo,
                pass: snap.val().clave
            })
            this.setState({usuario})
            console.log(this.state.usuario)
            localStorage.setItem('prueba',JSON.stringify(this.state.usuario[0]))
        });
    }

    validarUsuario(){
        const user = document.getElementById("inputUser").value;
        const pass = document.getElementById("inputPass").value;
      
        let local = JSON.parse(localStorage.getItem('prueba'))
        if(local.user == user){
           if(local.pass==pass){
               window.location.href="http://localhost:3000/Home"
           }else{
            alert("Error, Verifique datos")
           }
        }else{
            alert("Error, Verifique datos")
        }
    }

    render(){
        return(
            <div className="row justify-content-center mt-5">
        <div className="col-sm-6">
        <div className="card">
            <div className="card-header">
              <h1 className="text-center font-weight-light">INICIO DE SESION</h1>
            </div>
            <div className="card-body">
                <form>
                    <div className="form-group ">
                      <label for="inputUser">Usuario</label>
                      <input ref={input => {this.textUser = input;}} type="text" className="form-control" id="inputUser" placeholder="Ingresar Usuario"/>
                        </div>
                        <div className="form-group">
                      <label for="inputPass">Contraseña</label>
                      <input ref={input => {this.textPass = input;}} type="password" className="form-control" id="inputPass" placeholder="Ingresar Contraseña"/>
                        </div>
                        <div className="form-group">
                        <button type="button" onClick={this.validarUsuario}  className="btn btn-primary btn-lg btn-block">INGRESAR</button>
                         </div>
                        </form>
                        </div>
                     </div>
                </div>
         </div>
        );
    }
}

export default Login;

// examen-Angular/src/app/component/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router} from '@angular/router'
import { ConexionService } from '../../services/conexion.service';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor( private router: Router, private servicio: ConexionService) { }

  ngOnInit() {
  }
  usuario:any;
  titulo = "";
  validacion ="";
  alerta="";
  iniciar(usuario, clave){
    this.servicio.litarUsuario().subscribe(user=>{
      this.usuario = user;
      this.usuario.forEach(element => {
        if(element.usuario === usuario){
          if(element.clave === clave){
            this.router.navigate(['/tienda']);
          }else{
            this.titulo = "Error!!"
            this.validacion ="Porfavor, verifique contraseña y usuario"
            this.alerta ="alert alert-danger"
          }
        }else{
          this.titulo = "Error!!"
          this.alerta ="alert alert-danger"
          this.validacion ="Porfavor, verifique contraseña y usuario"
        }
      });
    })
  }



}

 <div class="row justify-content-center mt-5">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
              <h1 class="text-center font-weight-light">INICIO DE SESION</h1>
            </div>
            <div class="card-body">
                <form>
                    <div class="form-group ">
                      <label for="formGroupExampleInput">Usuario</label>
                      <input type="text" class="form-control {{alerta}}" id="formGroupExampleInput" placeholder="Ingresar Usuario" #usuario>
                    </div>
                    <div class="form-group">
                      <label for="formGroupExampleInput2">Contraseña</label>
                      <input type="password" class="form-control {{alerta}}" id="formGroupExampleInput2" placeholder="Ingresar Contraseña" #clave>
                    </div>
                    <div class="form-group">
                        <button (click)="iniciar(usuario.value, clave.value)" type="button" class="btn btn-primary btn-lg btn-block">INGRESAR</button>
                    </div>
                  </form>
            </div>
          </div>
    </div>
  </div>
